name: Spark Excel CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        sparkVersion: [ 3.0.1, 3.0.2, 3.0.3, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.2.2, 3.3.0 ]

    runs-on: ubuntu-latest

    steps:

      - name: Checkout with LFS
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Run tests and produce coverage
        run: sbt -DsparkVersion="${{matrix.sparkVersion}}" clean coverageOn test coverageReport

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/spark-${{ matrix.sparkVersion }}/scala-2.12/coverage-report/cobertura.xml
          env_vars: ${{ matrix.sparkVersion }}
          fail_ci_if_error: true
          name: spark-excel
          path_to_write_report: ./target/spark-${{ matrix.sparkVersion }}/scala-2.12/coverage-report/codecov_report.txt
          verbose: true

      - name: Create assembly
        if: ${{ github.event_name != 'pull_request' }}
        run: sbt -DsparkVersion="${{matrix.sparkVersion}}" clean coverageOff assembly

      - name: Upload the package
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2.2.4
        with:
          path: ./target/spark-${{ matrix.sparkVersion }}/scala-2.12/spark-excel*.jar
          if-no-files-found: warn
